"""Add integrated schema fields

Revision ID: d03355e19c6b
Revises: 01ca52f18921
Create Date: 2026-07-25 23:30:15.042082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd03355e19c6b'
down_revision: Union[str, Sequence[str], None] = '01ca52f18921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('heatmap_image_url', sa.String(), nullable=True))
    op.add_column('medical_records', sa.Column('prediction_result', sa.String(), nullable=True))
    op.add_column('medical_records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('medical_records', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('medical_records', 'r2_log_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('medical_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('ix_medical_records_status'), table_name='medical_records')
    op.create_index(op.f('ix_medical_records_user_id'), 'medical_records', ['user_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_medical_records_user_id'), table_name='medical_records')
    op.create_index(op.f('ix_medical_records_status'), 'medical_records', ['status'], unique=False)
    op.alter_column('medical_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('medical_records', 'r2_log_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('medical_records', 'file_size_bytes',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('medical_records', 'updated_at')
    op.drop_column('medical_records', 'prediction_result')
    op.drop_column('medical_records', 'heatmap_image_url')
    # ### end Alembic commands ###
